spring:
  application:
    name: datn
  http:
    encoding: UTF-8
    charset: UTF-8
    enable: true
  datasource:
    url: jdbc:mysql://localhost:3306/shoe
    username: root
    password: vuchitrieu
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format-sql: true
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: testEmail30122003@gmail.com
    password: syaw bejn tchf cwmh
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
springdoc:
  swagger-ui:
    config-url: /swagger-ui/index.html
  api-docs:
    path: /api

management:
  endpoint:
    health:
      show-details: always
server:
  port: 8080